// Generated by TinyCompiler

let x = 10;
let y = 5;
let sum = (x + y);
let diff = (x - y);
let product = (x * y);
let quotient = (x / y);
console.log(sum);
console.log(diff);
console.log(product);
console.log(quotient);
if ((x > y)) {
  console.log(x);
  let z = (x * 2);
  console.log(z);
} else {
  console.log(y);
}
let result = ((x + y) * (x - y));
console.log(result);
